version: 0.1

# This buildspec.yml can be built using the AWS managed codebuild image - aws/codebuild/ubuntu-base:14.04 or any other image that runs ubuntu and the aws sdk

phases:
  build:
    commands:
      - echo "******** Updating your website at s3 bucket ********"
      - echo "$TARGET_S3_BUCKET"
      - aws s3 sync * $TARGET_S3_BUCKET
